"""
carousel_content.py
Explicit slide-by-slide text content for all 16 carousel posts.

Each carousel has:
  - slide1: Cover / hero (generated from first dark slide prompt + COVER styling)
  - slide2: Dark slide 1 (Kie.ai generated — dark navy background)
  - slide3: Light slide 1 (white/light — not Kie.ai, built separately)
  - slide4: Dark slide 2
  - slide5: Light slide 2
  - slide6: Dark slide 3
  - slide7: Light slide 3
  - slide8: Dark slide 4 (final dark) — or CTA

Structure per entry:
  slides = [
      {"heading": "...", "body": "..."},   # slide 2 (dark)
      {"heading": "...", "body": "..."},   # slide 4 (dark)
      {"heading": "...", "body": "..."},   # slide 6 (dark)
      {"heading": "...", "body": "..."},   # slide 8 (dark / CTA)
  ]
"""

CAROUSEL_CONTENT = {

    # ── ID 83 — What Happens on Surgery Day ──────────────────────────────────
    83: {
        "topic": "What Happens on Surgery Day",
        "slides": [
            {
                "heading": "You Arrive",
                "body": "Check in 2 hours early. Nursing team greets you, consent is confirmed, IV line is placed."
            },
            {
                "heading": "Into Theatre",
                "body": "You're in theatre for 60–90 minutes. The anaesthetist keeps you comfortable throughout."
            },
            {
                "heading": "Recovery Room",
                "body": "You wake up in recovery. Pain is managed. Most patients are surprised by how calm it feels."
            },
            {
                "heading": "Walking Same Day",
                "body": "The physio visits within hours of surgery. Most patients take their first steps before dinner."
            },
        ]
    },

    # ── ID 95 — What Advanced Hip Replacements Look Like in 2026 ─────────────
    # NOTE: Kie.ai prompts for this carousel are set directly in posts_schedule.xlsx
    # from the JSON export (not generated by update_carousel_prompts.py).
    # The pipe-separated prompts in the Excel are the source of truth for ID 95.
    95: {
        "topic": "What advanced hip replacements look like in 2026",
        "slides": [
            {
                "heading": "Morning Light",
                "body": "Person sitting on a bed in morning light, head bowed, hand resting on knee — the quiet weight of waiting."
            },
            {
                "heading": "The Challenge Ahead",
                "body": "An empty staircase in warm afternoon light. For some patients, this is a daily obstacle that shouldn't have to be."
            },
            {
                "heading": "A Life Paused",
                "body": "A comfortable armchair beside a window overlooking a garden. The life you want is on the other side of this decision."
            },
            {
                "heading": "You Don't Have to Wait",
                "body": "The conversation that changes everything starts simply — with your GP, and then with a specialist."
            },
        ]
    },

    # ── ID 105 — Pre-Op Timeline ─────────────────────────────────────────────
    105: {
        "topic": "Pre-Op Preparation Timeline",
        "slides": [
            {
                "heading": "8 Weeks Out",
                "body": "Medical clearance. GP reviews your health, medications are adjusted, heart and lung checks done."
            },
            {
                "heading": "4 Weeks Out",
                "body": "Prehab begins. Strengthening your quads and glutes now dramatically speeds up recovery."
            },
            {
                "heading": "2 Weeks Out",
                "body": "Prepare your home. Raised toilet seat, shower chair, remove trip hazards, set up a recovery station."
            },
            {
                "heading": "1 Week Out",
                "body": "Final checks. Pre-op bloods, fasting instructions confirmed, support person arranged."
            },
        ]
    },

    # ── ID 113 — 5 Myths About Knee Replacement ──────────────────────────────
    113: {
        "topic": "5 Myths About Knee Replacement",
        "slides": [
            {
                "heading": "\"I'm Too Young\"",
                "body": "Age isn't the deciding factor — severity of arthritis and impact on your life is. People in their 50s have life-changing results."
            },
            {
                "heading": "\"I Should Wait Longer\"",
                "body": "Waiting too long weakens surrounding muscles and makes recovery harder. The right time is when quality of life is affected."
            },
            {
                "heading": "\"Recovery Takes a Year\"",
                "body": "Most patients are walking without aids in 6 weeks. Many return to normal activities within 3 months."
            },
            {
                "heading": "\"Implants Only Last 10 Years\"",
                "body": "Modern implants last 20–25+ years for the majority of patients. Technology has changed dramatically."
            },
        ]
    },

    # ── ID 124 — Activities After Knee Replacement ───────────────────────────
    124: {
        "topic": "Activities You Can Return to After Knee Replacement",
        "slides": [
            {
                "heading": "Walking",
                "body": "Most patients walk without aids within 4–6 weeks and build to long distances comfortably."
            },
            {
                "heading": "Swimming & Cycling",
                "body": "Low-impact exercise is ideal after 6–8 weeks. Many patients cycle recreationally again."
            },
            {
                "heading": "Golf & Travel",
                "body": "18 holes and long-haul flights are realistic goals for most patients within 3–4 months."
            },
            {
                "heading": "What to Avoid",
                "body": "High-impact running and contact sport are discouraged — but most patients don't miss them."
            },
        ]
    },

    # ── ID 134 — First 12 Weeks Recovery ─────────────────────────────────────
    134: {
        "topic": "Your First 12 Weeks After Surgery",
        "slides": [
            {
                "heading": "Weeks 1–2: Rest & Swell",
                "body": "Swelling peaks, but pain is well managed. Focus on elevation, icing and walking with your frame."
            },
            {
                "heading": "Weeks 3–6: Strength Returns",
                "body": "Physio intensifies. Stairs become easier. Most patients are off strong pain medication."
            },
            {
                "heading": "Weeks 6–8: Independence",
                "body": "Driving resumes (left knee: 2 weeks; right knee: 6 weeks). Daily life feels near-normal."
            },
            {
                "heading": "Weeks 8–12: Active Again",
                "body": "Walking distances increase. Social life resumes. Most patients say they wish they'd done it sooner."
            },
        ]
    },

    # ── ID 142 — Your Consultation Questions Answered ────────────────────────
    142: {
        "topic": "Your Consultation — Questions I Always Ask",
        "slides": [
            {
                "heading": "About Your Pain",
                "body": "Where is it, when is it worst, what makes it better? This tells me more than any scan."
            },
            {
                "heading": "About Your Function",
                "body": "What can't you do now that you used to? That gap between now and what you want is what we're solving."
            },
            {
                "heading": "Your Health History",
                "body": "Medications, prior surgeries, medical conditions — all influence the safest surgical plan for you."
            },
            {
                "heading": "Your Goals",
                "body": "Do you want to walk the Camino? Play with grandkids? Golf again? Knowing this shapes everything."
            },
        ]
    },

    # ── ID 148 — The Journey: 7 Steps ────────────────────────────────────────
    148: {
        "topic": "Your Knee Replacement Journey: 7 Steps",
        "slides": [
            {
                "heading": "Step 1–2: GP & Referral",
                "body": "Your GP recognises the arthritis is advanced and refers you to an orthopaedic surgeon."
            },
            {
                "heading": "Step 3–4: Consultation & Scans",
                "body": "We review your X-rays, examine your knee and discuss whether surgery is the right option."
            },
            {
                "heading": "Step 5: Pre-Op Preparation",
                "body": "Medical clearance, prehab exercises and home setup begin 6–8 weeks before your surgery date."
            },
            {
                "heading": "Steps 6–7: Surgery & Recovery",
                "body": "Surgery day → hospital → physio → home → back to life. Most patients are independent within 6 weeks."
            },
        ]
    },

    # ── ID 160 — 5 Things I Wish I'd Known ──────────────────────────────────
    160: {
        "topic": "5 Things Patients Wish They'd Known Before Surgery",
        "slides": [
            {
                "heading": "The First 48 Hours Are the Hardest",
                "body": "Pain and swelling peak early — but it quickly improves. Having this expectation changes everything."
            },
            {
                "heading": "Swelling Lasts Longer Than You Think",
                "body": "Some swelling at 3–6 months is completely normal. It doesn't mean something is wrong."
            },
            {
                "heading": "The Mental Side Is Real",
                "body": "Recovery has emotional ups and downs. Rest days feel like setbacks — they're not. Progress isn't linear."
            },
            {
                "heading": "They Wish They'd Done It Sooner",
                "body": "The most common thing patients say at 3 months: \"Why did I wait so long?\""
            },
        ]
    },

    # ── ID 166 — How Long Do Knee Implants Last ──────────────────────────────
    166: {
        "topic": "How Long Do Knee Implants Last?",
        "slides": [
            {
                "heading": "10 Years: 96% Intact",
                "body": "The vast majority of knee replacements are still performing well at the 10-year mark."
            },
            {
                "heading": "20 Years: 89% Intact",
                "body": "Long-term registry data shows most implants last two decades without needing revision."
            },
            {
                "heading": "25+ Years: 85% Intact",
                "body": "For patients in their 60s today, one knee replacement is likely to last the rest of their life."
            },
            {
                "heading": "What Affects Longevity",
                "body": "Weight, activity level and implant design all play a role. We discuss this individually at consultation."
            },
        ]
    },

    # ── ID 170 — Your Hip Questions Answered ─────────────────────────────────
    170: {
        "topic": "Your Hip Replacement Questions Answered",
        "slides": [
            {
                "heading": "How Long Is the Surgery?",
                "body": "Hip replacement typically takes 60–75 minutes. You're home within 2–3 days in most cases."
            },
            {
                "heading": "When Can I Drive?",
                "body": "Left hip: usually 2 weeks. Right hip: 6 weeks (until reaction time is safe). We confirm at review."
            },
            {
                "heading": "What About Airport Security?",
                "body": "Modern implants may trigger scanners. Carry a card from your surgeon — airlines and airports accept it."
            },
            {
                "heading": "How Long in Hospital?",
                "body": "Most patients are discharged within 48–72 hours and recovering well at home within the first week."
            },
        ]
    },

    # ── ID 178 — Why Waiting Makes Things Worse ──────────────────────────────
    178: {
        "topic": "Why Waiting Makes Things Worse",
        "slides": [
            {
                "heading": "Muscle Wasting",
                "body": "The longer you wait, the weaker your surrounding muscles become — making surgery and recovery harder."
            },
            {
                "heading": "Compensating Joints Suffer",
                "body": "When one hip or knee hurts, you shift load to the other side. That joint begins to deteriorate too."
            },
            {
                "heading": "Surgery Becomes More Complex",
                "body": "Severe bone loss, deformity and stiffness that develops from delay can significantly increase surgical difficulty."
            },
            {
                "heading": "Time Without Quality of Life",
                "body": "Every month of waiting is a month of reduced independence, reduced activity, and unnecessary pain."
            },
        ]
    },

    # ── ID 186 — Hip Replacement Timeline ───────────────────────────────────
    186: {
        "topic": "Hip Replacement: From Decision to Recovery",
        "slides": [
            {
                "heading": "Month 1–2: GP Visit",
                "body": "Pain is affecting daily life. GP orders X-rays and provides a referral to an orthopaedic surgeon."
            },
            {
                "heading": "Month 2–3: Specialist Consultation",
                "body": "We review imaging, examine your hip and discuss whether replacement is the right option for you."
            },
            {
                "heading": "Month 3–5: Pre-Op Preparation",
                "body": "Prehab, medical clearance, home setup and a confirmed surgery date. You are ready."
            },
            {
                "heading": "Month 6–7: Surgery & Recovery",
                "body": "Surgery → hospital → physio → home. Most patients are walking independently within 6 weeks."
            },
        ]
    },

    # ── ID 190 — What to Tell Your Family ───────────────────────────────────
    190: {
        "topic": "What to Tell Your Family Before Surgery",
        "slides": [
            {
                "heading": "What to Expect",
                "body": "Surgery day is calm. Swelling and fatigue in week one is normal. Progress is rapid after that."
            },
            {
                "heading": "How They Can Help",
                "body": "Meals, transport, company and encouragement in week one and two makes a measurable difference."
            },
            {
                "heading": "When to Be Concerned",
                "body": "Fever over 38.5°C, increasing redness, chest pain or sudden shortness of breath — call us immediately."
            },
            {
                "heading": "Week 6: Independence Returns",
                "body": "By six weeks most patients are managing independently. Families are often amazed at the transformation."
            },
        ]
    },

    # ── ID 202 — A Year of Questions ─────────────────────────────────────────
    202: {
        "topic": "The Questions I Get Asked Most",
        "slides": [
            {
                "heading": "\"Am I Ready for Surgery?\"",
                "body": "If arthritis is confirmed, conservative treatment has failed, and pain limits your life — you're ready."
            },
            {
                "heading": "\"Do I Need Both Knees Done?\"",
                "body": "Usually we do one at a time. Bilateral same-day surgery is occasionally appropriate — we discuss each case."
            },
            {
                "heading": "\"Can I Exercise While Waiting?\"",
                "body": "Yes — and you should. Swimming, cycling and walking protect the joint and improve your surgical outcome."
            },
            {
                "heading": "\"How Do I Choose a Surgeon?\"",
                "body": "Look for subspecialty training, volume of cases, registry data participation and clear communication."
            },
        ]
    },

    # ── ID 216 — While I'm on Leave ──────────────────────────────────────────
    216: {
        "topic": "What Happens While I'm on Leave",
        "slides": [
            {
                "heading": "Your Care Continues",
                "body": "A trusted covering surgeon is available for urgent post-operative concerns during my absence."
            },
            {
                "heading": "Urgent Concerns",
                "body": "Wound issues, fever, swelling or pain changes — contact the rooms. You will be seen or directed promptly."
            },
            {
                "heading": "True Emergencies",
                "body": "Chest pain, shortness of breath or suspected blood clot — go directly to your nearest emergency department."
            },
            {
                "heading": "I Return On...",
                "body": "My return date is confirmed. All patients with pending consultations or reviews have been rescheduled."
            },
        ]
    },

}


def get_slide_text(post_id: int) -> list[dict] | None:
    """Return the 4 dark-slide dicts for a carousel post, or None if not found."""
    entry = CAROUSEL_CONTENT.get(post_id)
    if entry:
        return entry["slides"]
    return None


def get_topic(post_id: int) -> str | None:
    """Return the topic string for a carousel post."""
    entry = CAROUSEL_CONTENT.get(post_id)
    if entry:
        return entry["topic"]
    return None


if __name__ == "__main__":
    # Quick sanity check — print all carousel IDs and slide counts
    print(f"Carousel content loaded for {len(CAROUSEL_CONTENT)} posts:\n")
    for pid, data in CAROUSEL_CONTENT.items():
        slides = data["slides"]
        print(f"  ID {pid:3d}  [{len(slides)} dark slides]  {data['topic']}")
