#!/usr/bin/env python3
"""
Excel → posts_data.py converter
Reads posts_schedule.xlsx and regenerates posts_data.py and posts_data2.py
"""

import sys, re, textwrap
from pathlib import Path

try:
    import openpyxl
except ImportError:
    print("Installing openpyxl...")
    import subprocess
    subprocess.run([sys.executable, "-m", "pip", "install", "openpyxl", "--break-system-packages", "-q"])
    import openpyxl

SCRIPT_DIR = Path(__file__).parent
EXCEL_PATH = SCRIPT_DIR / "posts_schedule.xlsx"
OUT1       = SCRIPT_DIR / "posts_data.py"
OUT2       = SCRIPT_DIR / "posts_data2.py"
SPLIT_AT   = 25   # posts 1-25 → posts_data.py, 26+ → posts_data2.py

HEADER = '''\
# All posts – captions, hashtags, image filenames
# ─────────────────────────────────────────────────
# DO NOT EDIT THIS FILE DIRECTLY.
# Edit posts_schedule.xlsx instead, then run:
#   Regenerate Posts from Excel.command
# ─────────────────────────────────────────────────

DISCLAIMER_IG = "\\n\\n\\u26a0\\ufe0f General educational information only. Individual treatment decisions should be made in consultation with your own medical team."
DISCLAIMER_FB = "\\n\\nThis post contains general educational information only. Please consult your GP or specialist for advice tailored to your situation."

POSTS = [
'''

FOOTER = "]\n"


def escape_for_python(text: str) -> str:
    """Make a string safe for use inside triple-quoted Python strings."""
    # Replace triple quotes to avoid breaking the string literal
    text = text.replace('"""', '\\"\\"\\"')
    return text


def row_to_dict(headers, row) -> dict:
    d = {}
    for h, cell in zip(headers, row):
        val = cell.value
        d[h] = str(val).strip() if val is not None else ""
    return d


def build_post_entry(d: dict) -> str:
    post_id         = d.get("ID", "")
    date            = d.get("Date", "")
    day             = d.get("Day", "")
    platform        = d.get("Platform", "")
    li_audience     = d.get("LI Audience", "")
    fmt             = d.get("Format", "")
    topic           = d.get("Topic", "")
    caption         = d.get("Caption", "")
    hashtags        = d.get("Hashtags", "")
    website_link    = d.get("Website Link", "")
    image_file      = d.get("Image File", "")
    image_prompt    = d.get("Image Prompt", "")

    caption_escaped = escape_for_python(caption)
    prompt_escaped  = escape_for_python(image_prompt)
    lines = [
        f'{{"id":{post_id},"date":"{date}","day":"{day}","platform":"{platform}","li_audience":"{li_audience}",',
        f'"format":"{fmt}","topic":"{topic}",',
        f'"caption":"""{caption_escaped}""",',
        f'"hashtags":"{hashtags}",',
        f'"website_link":"{website_link}","image_file":"{image_file}",',
        f'"nanobanana_prompt":"""{prompt_escaped}"""}},',
    ]
    return "\n".join(lines)


def main():
    if not EXCEL_PATH.exists():
        print(f"ERROR: {EXCEL_PATH} not found.")
        sys.exit(1)

    print(f"Reading {EXCEL_PATH}...")
    wb = openpyxl.load_workbook(EXCEL_PATH)
    ws = wb["Posts Schedule"]

    # Get headers from row 1
    headers = [cell.value for cell in ws[1]]

    posts = []
    for row in ws.iter_rows(min_row=2, values_only=False):
        if not any(cell.value for cell in row):
            continue
        d = {}
        for h, cell in zip(headers, row):
            val = cell.value
            d[h] = str(val).strip() if val is not None else ""
        posts.append(d)

    print(f"Found {len(posts)} posts")

    # Split into two files
    posts1 = [p for p in posts if int(p.get("ID", 0) or 0) <= SPLIT_AT]
    posts2 = [p for p in posts if int(p.get("ID", 0) or 0) >  SPLIT_AT]

    # Write posts_data.py
    with open(OUT1, "w", encoding="utf-8") as f:
        f.write(HEADER)
        for p in posts1:
            f.write("\n")
            f.write(build_post_entry(p))
            f.write("\n")
        f.write(FOOTER)
    print(f"Wrote {len(posts1)} posts to {OUT1.name}")

    # Write posts_data2.py
    with open(OUT2, "w", encoding="utf-8") as f:
        f.write(HEADER)
        for p in posts2:
            f.write("\n")
            f.write(build_post_entry(p))
            f.write("\n")
        f.write(FOOTER)
    print(f"Wrote {len(posts2)} posts to {OUT2.name}")

    # Quick syntax check
    print("Checking syntax...")
    import subprocess
    r1 = subprocess.run([sys.executable, "-c", f"import sys; sys.path.insert(0,'{SCRIPT_DIR}'); from posts_data import POSTS; print(f'posts_data: {{len(POSTS)}} posts OK')"], capture_output=True, text=True)
    r2 = subprocess.run([sys.executable, "-c", f"import sys; sys.path.insert(0,'{SCRIPT_DIR}'); from posts_data2 import POSTS; print(f'posts_data2: {{len(POSTS)}} posts OK')"], capture_output=True, text=True)
    if r1.returncode == 0:
        print(r1.stdout.strip())
    else:
        print("WARNING: posts_data.py has syntax errors:", r1.stderr[:200])
    if r2.returncode == 0:
        print(r2.stdout.strip())
    else:
        print("WARNING: posts_data2.py has syntax errors:", r2.stderr[:200])

    print("\n✅ Done! Run 'Push Data Fixes to GitHub.command' to push changes.")


if __name__ == "__main__":
    main()
