# All posts – captions, hashtags, image filenames
# ─────────────────────────────────────────────────
# DO NOT EDIT THIS FILE DIRECTLY.
# Edit posts_schedule.xlsx instead, then run:
#   Regenerate Posts from Excel.command
# ─────────────────────────────────────────────────

DISCLAIMER_IG = "\n\n\u26a0\ufe0f General educational information only. Individual treatment decisions should be made in consultation with your own medical team."
DISCLAIMER_FB = "\n\nThis post contains general educational information only. Please consult your GP or specialist for advice tailored to your situation."

POSTS = [

{"id":1,"date":"2026-04-09","day":"Thursday","platform":"Instagram","li_audience":"",
"format":"Carousel","topic":"What Is Hip Arthritis?",
"caption":"""What happens inside your hip when arthritis develops? 🦴

Swipe through to understand hip arthritis from the inside out — what it is, how it progresses, and what your treatment options are.

🔹 The hip is a ball-and-socket joint. Smooth cartilage lets it move without pain.
🔹 Osteoarthritis gradually wears that cartilage away — leaving bone rubbing on bone.
🔹 The result: deep groin pain, morning stiffness, difficulty putting on shoes or socks.

Most cases are managed without surgery for a long time — physiotherapy, weight management, activity modification, and appropriate analgesia. Surgery is considered when those measures are no longer sufficient.

If hip pain is affecting your sleep, your mobility, or your quality of life — a conversation with your GP is the right first step.

Dr Chien-Wen Liew | Adelaide Hip & Knee Replacement Surgeon
Orthopaedics 360 | drchienwenliew.com.au 🔗 Link in bio

⚠️ General educational information only. Individual treatment decisions should be made in consultation with your own medical team.""",
"hashtags":"#HipArthritis #HipReplacement #AdelaideOrthopaedicSurgeon #Orthopaedics360 #JointHealth #Osteoarthritis #ArthritisAwareness #HipHealth #PatientEducation #AdelaideHealth #DrChienWenLiew #BoneHealth #HipPain",
"website_link":"https://drchienwenliew.com.au/blog/hip-arthritis/","image_file":"2026-04-09-instagram.jpg",
"nanobanana_prompt":""},

{"id":2,"date":"2026-04-10","day":"Friday","platform":"LinkedIn","li_audience":"",
"format":"Article","topic":"When Should a GP Refer for Hip Replacement?",
"caption":"""When should a GP refer a patient for hip replacement? This is a question I receive regularly from colleagues, and it’s worth addressing clearly.

The short answer: earlier than many practitioners assume.

There is a persistent misconception that referral should wait until a patient is “bone on bone” on imaging or severely debilitated. The evidence does not support this threshold.

What actually guides surgical consideration is the clinical triad of:

1. Persistent, functionally significant symptoms — pain affecting sleep, mobility, and daily activities despite adequate conservative management
2. Failed non-surgical treatment — a genuine trial of physiotherapy, analgesia, weight management, and activity modification
3. Patient goals — understanding what the patient is hoping to achieve, and whether surgery can realistically deliver that

Key clinical indicators for referral:
▸ Hip pain persisting > 6 months despite conservative management
▸ Night pain consistently affecting sleep quality
▸ Functional limitations affecting ADLs, work, or social participation
▸ Radiological J2-J3 joint space narrowing correlating with symptoms

Importantly, earlier referral allows pre-operative optimisation — addressing BMI, anaemia, glucose control, and cardiovascular risk — which meaningfully improves surgical outcomes and recovery.

If you’d like to discuss a patient informally before referring, I welcome that conversation. Referrals to Orthopaedics 360 can be sent to drliew@orthopaedics360.com.au or via Medical Objects.

What factors most commonly lead you to delay referral? I’d welcome your perspective in the comments.

#Orthopaedics #GPReferral #TotalHipReplacement #ArthroplastyAustralia #AdelaideOrthopedics #MedEd #HipSurgeon #JointReplacement""",
"hashtags":"",
"website_link":"https://drchienwenliew.com.au/blog/what-is-a-total-hip-replacement/","image_file":"2026-04-10-linkedin.jpg",
"nanobanana_prompt":""},

{"id":3,"date":"2026-04-12","day":"Sunday","platform":"Instagram","li_audience":"",
"format":"Infographic","topic":"5 Signs You Might Need a Knee Replacement",
"caption":"""5 signs your knee might need more than just physio 👇

These aren’t definitive indicators — but they’re worth a conversation with your GP if they sound familiar.

1️⃣ Pain that wakes you at night, consistently, despite medication
2️⃣ Morning stiffness lasting more than 30 minutes, day after day
3️⃣ You’ve stopped doing the things you love because of your knee
4️⃣ Pain medication is no longer providing adequate relief
5️⃣ You’re walking differently to protect the painful side

None of these automatically means surgery. But all of them mean it’s time to get properly assessed.

The right pathway starts with your GP — who can assess, manage, refer, or simply reassure you.

Dr Chien-Wen Liew | Adelaide Hip & Knee Replacement Surgeon
More at drchienwenliew.com.au 🔗 Link in bio

⚠️ General educational information only. Individual treatment decisions should be made in consultation with your own medical team.""",
"hashtags":"#KneeReplacement #KneeArthritis #KneePain #AdelaideOrthopaedicSurgeon #Orthopaedics360 #TotalKneeReplacement #KneeHealth #JointHealth #PatientEducation #AdelaideHealth #Osteoarthritis #DrChienWenLiew",
"website_link":"https://drchienwenliew.com.au/blog/total-knee-replacement-adelaide/","image_file":"2026-04-12-instagram.jpg",
"nanobanana_prompt":""},

{"id":4,"date":"2026-04-13","day":"Monday","platform":"LinkedIn","li_audience":"",
"format":"Post","topic":"Dr Liew's Approach to Total Joint Replacement",
"caption":"""What guides my decision-making in the operating room?

I’m asked this regularly, and I want to be direct about what I believe matters most in total joint replacement.

The surgical technique — incision, implant choice, bone cuts, soft tissue balance — is important. But it is one component of a larger system. What I’ve come to prioritise in my practice:

Patient selection and timing. Operating on the right patient, at the right time, for the right reason. Pre-operative optimisation — managing BMI, anaemia, glucose control, medications — fundamentally changes outcomes.

Precision over speed. Taking the time intra-operatively to achieve accurate alignment, balanced soft tissue tension, and correct implant positioning. These details have long-term implications for both function and implant survivorship.

Rehabilitation as part of the operation. The procedure doesn’t end at wound closure. Post-operative physiotherapy, patient education, and follow-up protocol are integral to the result.

Honest consent. Being direct with patients about what surgery can and cannot achieve for them specifically. Managing expectations — not dampening hope, but grounding it in the patient’s reality.

I operate at Eastwood Private Hospital in Adelaide, with a practice focused exclusively on hip and knee replacement.

Happy to connect with GP colleagues or discuss cases informally.

#Arthroplasty #TotalJointReplacement #HipSurgeon #KneeSurgeon #OrthopaedicSurgery #AdelaideOrthopedics #SurgicalTechnique #MedEd""",
"hashtags":"",
"website_link":"https://drchienwenliew.com.au/blog/my-reasoning-for-total-hip-replacements/","image_file":"2026-04-13-linkedin.jpg",
"nanobanana_prompt":""},

{"id":5,"date":"2026-04-14","day":"Tuesday","platform":"Instagram","li_audience":"",
"format":"Post","topic":"Am I Too Old for a Hip Replacement?",
"caption":""""Am I too old for a hip replacement?"

This is one of the most common questions I hear in clinic. And the evidence-based answer is: age alone is not a contraindication.

What the research consistently shows:

📊 Data from the Australian Orthopaedic Association National Joint Replacement Registry (AOANJRR) shows that patients in their 70s and 80s achieve meaningful functional improvement and report high satisfaction following total hip arthroplasty.

What matters more than age:
→ Overall medical fitness (cardiovascular, respiratory, renal)
→ Cognitive function and ability to engage with rehabilitation
→ Degree of functional limitation caused by the joint
→ Whether conservative management has been adequately trialled

Older patients may carry higher anaesthetic risk — which is assessed carefully before surgery. But many patients in their 70s and 80s are excellent surgical candidates.

If you’ve been told you’re “too old” without a thorough assessment — it’s worth seeking a specialist opinion.

Full guide at drchienwenliew.com.au 🔗 Link in bio

⚠️ General educational information only. Individual treatment decisions should be made in consultation with your own medical team.""",
"hashtags":"#HipReplacement #AgeAndSurgery #AdelaideOrthopaedicSurgeon #TotalHipReplacement #Osteoarthritis #JointHealth #Orthopaedics360 #HipHealth #AdelaideHealth #PatientEducation #Arthroplasty #DrChienWenLiew",
"website_link":"https://drchienwenliew.com.au/blog/am-i-too-old-for-a-hip-or-knee-replacement/","image_file":"2026-04-14-instagram.jpg",
"nanobanana_prompt":""},

{"id":6,"date":"2026-04-14","day":"Tuesday","platform":"Facebook","li_audience":"",
"format":"Post + Link","topic":"Am I Too Old for a Hip Replacement?",
"caption":""""Am I too old for a hip replacement?"

It’s one of the questions I hear most often in clinic — and in many cases, the honest answer is: no.

Age is one consideration among many. What we actually assess before recommending surgery includes overall health and medical fitness, functional limitation and quality of life impact, cognitive function and ability to engage with rehabilitation, and whether conservative options like physiotherapy and pain management have been adequately explored.

Data from the Australian Orthopaedic Association National Joint Replacement Registry consistently shows that patients in their 70s and 80s achieve meaningful improvements in pain and function following total hip arthroplasty, with satisfaction rates that compare well with younger age groups.

If you or a family member has been putting off a conversation about hip replacement because of age concerns, the right first step is a GP referral for a specialist assessment. A proper evaluation will give you much clearer information about what is and isn’t appropriate for your situation.

I’ve written a detailed guide on this topic — you can read it at the link below.

This post contains general educational information only. Please consult your GP or specialist for advice tailored to your situation.""",
"hashtags":"#AdelaideHealth #HipReplacement #JointHealth #OrthopaedicSurgery #SouthAustralia #Orthopaedics360",
"website_link":"https://drchienwenliew.com.au/blog/am-i-too-old-for-a-hip-or-knee-replacement/","image_file":"2026-04-14-facebook.jpg",
"nanobanana_prompt":""},

{"id":7,"date":"2026-04-16","day":"Thursday","platform":"Instagram","li_audience":"",
"format":"Carousel","topic":"5 Myths About Knee Replacement — Debunked",
"caption":"""Let’s bust 5 of the most common myths about knee replacement 💡

Swipe to get the evidence-based truth on each one →

"They only last 10-15 years" Current evidence shows that they have average survival of 92% at 20 years. 

"You can't be active" Whilst running isn't recommended, everything else is on the cards!

"You can't kneel" Check out my video on youtube about kneeling

"Your other knee will get worse after surgery" No! Its just that the first knee we do won't hurt anymore!

Visit drchienwenliew.com.au to learn more.""",
"hashtags":"#KneeReplacement #TotalKneeReplacement #KneeMyths #MedicalMyths #AdelaideOrthopaedicSurgeon #Orthopaedics360 #KneeHealth #Osteoarthritis #JointHealth #PatientEducation #AdelaideHealth #DrChienWenLiew",
"website_link":"https://drchienwenliew.com.au/blog/knee-replacement-techniques/","image_file":"2026-04-16-instagram.jpg",
"nanobanana_prompt":""},

{"id":8,"date":"2026-04-17","day":"Friday","platform":"LinkedIn","li_audience":"",
"format":"Post","topic":"My Lateral Curved Incision for TKR",
"caption":"""My approach to the skin incision in total knee replacement — and the rationale behind using a lateral curved technique.

The traditional midline anterior incision in TKR is well-established and reliable. Over time, I have moved towards a lateral curved approach for most of my primary total knee replacements, and I want to explain why.

The lateral parapatellar skin incision — curving laterally over the tibial tubercle — offers several theoretical advantages aligned with my intra-operative goals:

→ Improved skin edge vascularity. The dominant blood supply to the anterior knee skin runs medially. A laterally placed incision creates a flap with better perfusion, which may reduce wound edge complications.

→ The ability to kneel improves significantly when we don't cut over the area you kneel on

→ Cosmetically, it looks nicer because its curved, and isn't as noticeable when looking at it from the front. 

I want to be clear: the incision is the access. What happens through it — alignment, implant positioning, bone cuts, soft tissue balancing — remains the primary determinant of functional outcome.

This is one element of a multifaceted procedure, and I share it here as a point of professional discussion rather than a claim of superiority over other approaches. Different patient anatomy and pathology may favour different techniques.

Happy to discuss with any colleagues considering a similar approach.

#TotalKneeReplacement #SurgicalTechnique #Arthroplasty #KneeSurgeon #AdelaideOrthopedics #MedEd #OrthopedicSurgery""",
"hashtags":"",
"website_link":"https://drchienwenliew.com.au/blog/my-lateral-curved-incision-for-total-knee-replacements/","image_file":"2026-04-17-linkedin.jpg",
"nanobanana_prompt":""},

{"id":9,"date":"2026-04-19","day":"Sunday","platform":"Instagram","li_audience":"",
"format":"Post","topic":"What Happens on the Day of Surgery?",
"caption":"""Surgery day: what actually happens from the moment you arrive? 🏥

Knowing what to expect is one of the most effective ways to reduce pre-operative anxiety. Here’s a plain-English walkthrough.

🌅 Before surgery:
→ Arrive 1–2 hours before your scheduled time
→ Nursing team completes pre-op checks, consent, and preparation
→ You’ll meet the anaesthetist to discuss your pain management plan
→ The surgical team will mark the correct side

🔬 In theatre:
→ Most hip and knee replacements take 1–2 hours
→ General anaesthetic or spinal block (often combined)
→ Multimodal anaesthesia protocol to minimise post-op pain

🛌 After surgery:
→ Recovery room monitoring until stable
→ Physiotherapy usually begins the same day — sitting up, weight-bearing
→ Most patients stay 1–3 nights in hospital

Questions about your specific procedure? Visit drchienwenliew.com.au 🔗 Link in bio

⚠️ General educational information only. Individual treatment decisions should be made in consultation with your own medical team.""",
"hashtags":"#SurgeryDay #HipReplacement #KneeReplacement #JointReplacement #AdelaideOrthopaedicSurgeon #Orthopaedics360 #PatientJourney #WhatToExpect #AdelaideHealth #OrthopedicSurgery #Arthroplasty #DrChienWenLiew",
"website_link":"https://drchienwenliew.com.au/blog/what-happens-on-the-day-of-a-hip-or-knee-replacement/","image_file":"2026-04-19-instagram.jpg",
"nanobanana_prompt":""},

{"id":10,"date":"2026-04-20","day":"Monday","platform":"LinkedIn","li_audience":"",
"format":"Post","topic":"Direct Anterior Approach for THA — Clinical Advantages and Patient Selection",
"caption":"""The direct anterior approach (DAA) for total hip arthroplasty: clinical rationale and patient selection criteria.

The DAA has become an important part of my surgical practice for primary total hip replacement. It is not the ONLY method I perform

What the literature supports:

The DAA is an intermuscular, internervous approach that preserves the posterior hip stabilisers. Compared to posterior approaches, there is reasonable evidence for:

• Earlier return to independent walking and reduced mobility aid use in the immediate post-operative period
• Lower dislocation rates in suitable patients, given preservation of posterior soft tissue integrity
• Potential for earlier discharge in appropriately selected patients

What it does not guarantee:

The DAA has its own complication profile — particularly around femoral stem preparation and acetabular component positioning in patients with challenging anatomy. Higher BMI, muscular thighs, limited pre-operative ROM, and prior hip surgery all increase technical difficulty.

My patient selection criteria for DAA:
▸ No significant ceongenital abnormalities (ie severe dysplasia)
▸ A fused hip

I use the DAA routinely for all patients. I no longer offer anything else. The approach should serve the patient.

Open to discussion with colleagues on selection criteria or specific cases.

#AnteriorHipReplacement #DirectAnteriorApproach #TotalHipReplacement #HipSurgeon #Arthroplasty #AdelaideOrthopedics #SurgicalTechnique #MedEd""",
"hashtags":"",
"website_link":"https://drchienwenliew.com.au/blog/direct-anterior-approach/","image_file":"2026-04-20-linkedin.jpg",
"nanobanana_prompt":""},

{"id":11,"date":"2026-04-21","day":"Tuesday","platform":"Instagram","li_audience":"",
"format":"Infographic","topic":"The Hip Joint: A Visual Guide",
"caption":"""Your hip joint, explained simply 🦴

Most people know the hip is a “ball and socket” joint — but understanding the anatomy helps make sense of what can go wrong and why treatment works the way it does.

The key structures:

🔵 Femoral head — the rounded “ball” at the top of the thigh bone
🔵 Acetabulum — the cup-shaped socket in the pelvis
🔵 Articular cartilage — the smooth layer covering both surfaces
🔵 Joint capsule — the fibrous sleeve holding the joint together
🔵 Synovial fluid — the natural lubricant inside the joint

In osteoarthritis, the cartilage gradually wears away. Without that cushioning layer, bone rubs on bone — causing pain, inflammation, stiffness, and reduced range of motion.

Understanding your anatomy is the first step to understanding your options.

More at drchienwenliew.com.au 🔗 Link in bio

⚠️ General educational information only. Individual treatment decisions should be made in consultation with your own medical team.""",
"hashtags":"#HipAnatomy #HipJoint #HipArthritis #Orthopaedics360 #AdelaideOrthopaedicSurgeon #PatientEducation #HipHealth #Osteoarthritis #AdelaideHealth #BoneHealth #JointHealth #DrChienWenLiew",
"website_link":"https://drchienwenliew.com.au/blog/what-is-a-total-hip-replacement/","image_file":"2026-04-21-instagram.jpg",
"nanobanana_prompt":""},

{"id":12,"date":"2026-04-21","day":"Tuesday","platform":"Facebook","li_audience":"",
"format":"Post + Link","topic":"Am I Too Young for a Knee Replacement?",
"caption":""""Am I too young for a knee replacement?"

This is an important conversation — and the answer is more nuanced than a simple yes or no.

The concern is understandable. Knee implants have a finite lifespan, and younger patients may outlive their first replacement, potentially requiring revision surgery later. This is a real factor that should be part of any shared decision-making conversation.

But “too young” is sometimes cited as a reason to delay surgery when the more relevant question is: how significantly is the arthritis affecting this patient’s quality of life, and have conservative options been genuinely exhausted?

For patients in their 40s and 50s with severe, bilateral knee arthritis and failed conservative management, continued suffering while waiting for an “appropriate” age is not always in their best interest.

Modern knee implants are highly durable. Australian registry data shows that at 10 years there is 92% survival of inplants in all patients who had their implant under 55yo. 

This decision should involve a specialist who knows your case, your goals, and your imaging.

Dr Liew’s full guide on this topic is at the link below.

This post contains general educational information only. Please consult your GP or specialist for advice tailored to your situation.""",
"hashtags":"#AdelaideHealth #KneeReplacement #JointHealth #OrthopaedicSurgery #SouthAustralia #Arthroplasty",
"website_link":"https://drchienwenliew.com.au/blog/am-i-too-young-for-a-hip-or-knee-replacement/","image_file":"2026-04-21-facebook.jpg",
"nanobanana_prompt":""},

{"id":13,"date":"2026-04-23","day":"Thursday","platform":"Instagram","li_audience":"",
"format":"Carousel","topic":"Recovery Timeline After Total Knee Replacement",
"caption":"""What to expect after total knee replacement — week by week ⏱️

Swipe through for a realistic, evidence-based timeline from Day 1 to 12 months →

One of the most common questions before surgery is: “How long will recovery take?”

The honest answer is that it varies — but there are predictable milestones that most patients reach.

A few important things to know:

✅ Most patients are walking on the same day as surgery (with support)
✅ You’ll typically be home within 2–4 days
✅ The first 6 weeks involve the most active rehabilitation work
✅ Driving often resumes around 2-3 weeks (right knee, automatic car)
✅ Continued improvement happens usually within 6-9 months but can take up to 12 months post-op

Dr Chien-Wen Liew | Adelaide Hip & Knee Replacement Surgeon
Full recovery information at drchienwenliew.com.au 🔗 Link in bio

⚠️ General educational information only. Individual treatment decisions should be made in consultation with your own medical team.""",
"hashtags":"#KneeReplacement #TKR #KneeReplacementRecovery #Orthopaedics360 #AdelaideOrthopaedicSurgeon #JointReplacement #RecoveryTimeline #PatientJourney #PostOpCare #AdelaideHealth #Arthroplasty #DrChienWenLiew",
"website_link":"https://drchienwenliew.com.au/blog/total-knee-replacement-adelaide/","image_file":"2026-04-23-instagram.jpg",
"nanobanana_prompt":""},

{"id":14,"date":"2026-04-24","day":"Friday","platform":"LinkedIn","li_audience":"",
"format":"Post","topic":"Hip vs Knee Arthritis — Differentiating for Referral",
"caption":"""Hip arthritis vs knee arthritis: a clinical pearl worth revisiting.

One of the more common sources of diagnostic delay I encounter is the overlap between hip and knee pain presentation. Patients — and sometimes referring practitioners — attribute groin and anterior thigh pain to the knee, while lateral knee or distal thigh pain may actually originate from the hip. Getting this right matters for appropriate referral and workup.

Key differentiating clinical features:

Hip OA typically presents with:
• Groin pain (primary) — often radiating to anterior thigh, and sometimes referred to the knee
• Pain with weight-bearing and passive internal rotation
• Reduced hip ROM — particularly internal rotation and extension
• Positive Stinchfield test (resisted hip flexion reproduces pain)
• Morning stiffness < 30 minutes

Knee OA typically presents with:
• Joint line tenderness, anterior or medial knee pain
• Effusion, crepitus, reduced ROM
• Pain at extremes of flexion/extension and with stairs

Critical clinical pearl: Hip OA frequently presents as knee pain — particularly in patients where knee imaging doesn’t fully account for their symptom severity. Always examine the hip when assessing knee pain.

Imaging guidance: weight-bearing AP pelvis + lateral hip for suspected hip OA; weight-bearing AP, lateral and skyline views for knee OA.

Happy to discuss referral cases informally before you send them through.

#Orthopaedics #HipArthritis #KneeArthritis #GPReferral #AdelaideOrthopedics #DiagnosticPearl #MedEd #ArthroplastyAustralia""",
"hashtags":"",
"website_link":"https://drchienwenliew.com.au/blog/osteoarthritis-on-hip-and-knee-xrays/","image_file":"2026-04-24-linkedin.jpg",
"nanobanana_prompt":""},

{"id":15,"date":"2026-04-26","day":"Sunday","platform":"Instagram","li_audience":"",
"format":"Post","topic":"Hip vs Knee Arthritis — Patient Guide",
"caption":"""Hip pain or knee pain? Sometimes it’s harder to tell than you’d think 🤔

Here’s a quick guide to help you understand the difference — and why it matters.

🔵 Hip arthritis typically causes:
→ Deep groin pain (sometimes felt in the thigh or even the knee)
→ Stiffness when getting up from a chair
→ Difficulty putting on socks or shoes
→ A limp, especially later in the day

🔵 Knee arthritis typically causes:
→ Pain at the front, inside, or outside of the knee
→ Swelling and warmth around the joint
→ Creaking or grinding with movement
→ Pain on stairs or when getting up from low chairs

Here’s the twist: hip arthritis can cause pain that feels like it’s coming from the knee. This is called referred pain — and it’s why a proper clinical examination (not just imaging) is so important.

If you’re not sure which joint is causing your pain, your GP or I can help sort this out.

Dr Chien-Wen Liew | Adelaide Hip & Knee Replacement Surgeon
Learn more at drchienwenliew.com.au

⚠️ General educational information only. Individual treatment decisions should be made in consultation with your own medical team.""",
"hashtags":"#HipArthritis #KneeArthritis #JointPain #Osteoarthritis #AdelaideOrthopaedicSurgeon #Orthopaedics360 #PatientEducation #HipPain #KneePain #AdelaideHealth #JointHealth #DrChienWenLiew",
"website_link":"https://drchienwenliew.com.au/blog/osteoarthritis-on-hip-and-knee-xrays/","image_file":"2026-04-26-instagram.jpg",
"nanobanana_prompt":""},

{"id":16,"date":"2026-04-27","day":"Monday","platform":"LinkedIn","li_audience":"",
"format":"Post","topic":"Pre-Operative Optimisation Before TJR",
"caption":"""Pre-operative optimisation: what I ask of patients before total joint replacement — and why it matters clinically.

The surgery itself is one part of a successful joint replacement outcome. What happens in the weeks leading up to theatre has a significant and measurable impact on recovery, complication rates, and patient satisfaction.

The areas I focus on most consistently:

BMI management. Obesity is associated with increased surgical risk, higher rates of wound complications, infection, and implant loosening. I have an honest conversation with patients about weight and will, in some cases, recommend deferral pending meaningful weight loss. This is a clinical decision, not an aesthetic one.

Anaemia. Pre-operative anaemia is a modifiable risk factor associated with increased allogeneic blood transfusion, longer hospital stay, and higher complication rates. I routinely screen and refer for iron infusion or haematological review where indicated.

Glucose optimisation. In patients with Type 2 diabetes, HbA1c > 8.5% significantly increases the risk of surgical site infection. A conversation with the patient’s GP or endocrinologist before listing is standard in my practice.

Medication review. Anticoagulants, immunosuppressants, and some supplements require management around the peri-operative period. Shared communication between the surgeon, anaesthetist, and GP prevents avoidable complications.

Physiotherapy “prehab.” There is emerging evidence supporting pre-operative exercise to improve post-operative recovery — particularly quadriceps strengthening before TKR.

If you’re referring a patient for joint replacement, flagging these issues early allows time for optimisation before listing.

#Arthroplasty #PreOperativeOptimisation #TotalJointReplacement #GPReferral #MedEd #AdelaideOrthopedics #HipReplacement #KneeReplacement""",
"hashtags":"",
"website_link":"https://drchienwenliew.com.au/blog/nutrition-and-joint-replacements/","image_file":"2026-04-27-linkedin.jpg",
"nanobanana_prompt":""},

{"id":17,"date":"2026-04-28","day":"Tuesday","platform":"Instagram","li_audience":"",
"format":"Quote Card","topic":"Dr Liew Quote — Restoring Quality of Life",
"caption":"""My goal has never just been to replace a joint.

It’s to give someone their life back. 💙

The measure of a successful operation isn’t what I see in the X-ray. It’s whether a patient can walk to the letterbox again. Take their grandchildren to the park. Sleep through the night without pain. And live the activity level they want...even if its skiing at Hotham with the whole family. 

That’s what this work is about.

— Dr Chien-Wen Liew
Adelaide Hip & Knee Replacement Surgeon
Orthopaedics 360 | drchienwenliew.com.au""",
"hashtags":"#Orthopaedics360 #AdelaideOrthopaedicSurgeon #HipReplacement #KneeReplacement #DrChienWenLiew #JointReplacement #AdelaideHealth #PatientCare #MedicalProfessional #WhyIMedicine",
"website_link":"https://drchienwenliew.com.au/blog/orthopaedics-in-south-australia/","image_file":"2026-04-28-instagram.jpg",
"nanobanana_prompt":""},

{"id":18,"date":"2026-04-28","day":"Tuesday","platform":"Facebook","li_audience":"",
"format":"Post + Link","topic":"Pre-Operative Information for Hip & Knee Surgery",
"caption":"""Preparing for hip or knee replacement? Here’s what to know before surgery.

Good preparation genuinely makes a difference to your recovery. Here are the key things most patients need to organise in the weeks before their procedure.

Medical clearances: Your GP will typically need to review your overall health, blood tests, and any cardiac or respiratory conditions before surgery.

Medications: Tell your surgical team about everything you take, including supplements and blood thinners. Some will need to be stopped or adjusted. Importantly, new medications such as Mounjaro and Ozempic have differences in your pre-op fasting

Your home: Set up before you go in. Organise grab rails in the bathroom, raise your toilet seat if needed, remove loose rugs, and prepare a recovery station with everything you’ll need within easy reach.

Support at home: Arrange a carer or family member for the first 1–2 weeks. You won’t be able to drive immediately after surgery.

Fitness: If possible, start gentle exercises before surgery. Your physiotherapist or GP can guide you on what’s safe and helpful.

We’ve put together a detailed pre-operative guide at the link below — it covers everything from your pre-admission appointment to what to bring on the day.

This post contains general educational information only. Please consult your GP or specialist for advice tailored to your situation.""",
"hashtags":"#AdelaideHealth #HipReplacement #KneeReplacement #SurgeryPrep #SouthAustralia #Orthopaedics360",
"website_link":"https://drchienwenliew.com.au/blog/faq-total-hip-replacement/","image_file":"2026-04-28-facebook.jpg",
"nanobanana_prompt":""},

{"id":19,"date":"2026-04-30","day":"Thursday","platform":"Instagram","li_audience":"",
"format":"Carousel","topic":"5 Exercises to Help Before Your Knee Replacement",
"caption":"""Your knee is about to be replaced — but what you do beforehand matters. 🏃‍♀️

Swipe through 5 exercises that can help you prepare physically for knee replacement surgery →

Research suggests that “prehab” — strengthening the muscles around the knee before surgery — can support a faster recovery post-operatively.

Static quads activities are important. 

Practicing using a walking aid

Activating Gluteals and core musculature. 

Dr Chien-Wen Liew | Adelaide Hip & Knee Replacement Surgeon
Full patient information at drchienwenliew.com.au 🔗 Link in bio

⚠️ General educational information only. Individual treatment decisions should be made in consultation with your own medical team.""",
"hashtags":"#KneePrehab #KneeReplacement #TKR #ExerciseBeforeSurgery #AdelaideOrthopaedicSurgeon #Orthopaedics360 #PhysioLife #JointHealth #KneeHealth #PatientJourney #AdelaideHealth #DrChienWenLiew",
"website_link":"https://drchienwenliew.com.au/blog/nutrition-and-joint-replacements/","image_file":"2026-04-30-instagram.jpg",
"nanobanana_prompt":""},

{"id":20,"date":"2026-05-01","day":"Friday","platform":"LinkedIn","li_audience":"",
"format":"Post","topic":"Post-Operative Complication Prevention in TJR",
"caption":"""Post-operative complication prevention in total joint replacement: the protocols that matter most.

Complication prevention in joint replacements is not a single intervention — it is a system. Here is how our team approaches the key risk areas at Eastwood Private Hospital.

Surgical site infection (SSI):
Pre-operative skin preparation, prophylactic antibiotics within 5 minutes of incision, strict theatre protocol, and wound management. In high-risk patients (diabetes, obesity, immunosuppression), additional precautions and extended monitoring are applied.

Venous thromboembolism (VTE):
We use a risk-stratified VTE prophylaxis protocol. Most patients receive pharmacological prophylaxis (enoxaparin or oral anticoagulant) for 2–6 weeks post-operatively, combined with mechanical prophylaxis (compression stockings, early mobilisation). Patient education about DVT signs and symptoms is part of our discharge routine.

Peri-prosthetic joint infection (PJI):
Any patient with existing dental disease, skin conditions, or potential bacteraemia source is reviewed pre-operatively. The impact of antibiotic prophylaxis timing and wound care on PJI rates is well-documented in the literature.

Dislocation:
Patient-specific risk stratification (approach, anatomy, prior surgery) guides our dislocation precautions advice. For DAA patients, posterior precautions are not required. We use a consistent patient education protocol regardless of approach.

For GP colleagues: early recognition of post-operative complications is important. If you see a patient post-TJR with fever, wound breakdown, increasing pain, or swelling, please don’t hesitate to contact our rooms directly.

#TotalJointReplacement #ComplicationPrevention #ArthroplastyAustralia #GPReferral #MedEd #Orthopaedics #HipReplacement #KneeReplacement""",
"hashtags":"",
"website_link":"https://drchienwenliew.com.au/blog/total-hip-replacement-risk-factors/","image_file":"2026-05-01-linkedin.jpg",
"nanobanana_prompt":""},

{"id":21,"date":"2026-05-03","day":"Sunday","platform":"Instagram","li_audience":"",
"format":"Post","topic":"BMI and Joint Replacement Surgery",
"caption":"""Something I want patients to understand about BMI and joint replacement surgery. 💬

This is a topic that requires honesty, not judgment.

Higher BMI is associated with increased surgical risk in total joint replacement, including:
→ Higher rates of wound complications and infection
→ Increased anaesthetic risk
→ Higher risk of implant wear and loosening over time
→ Longer recovery periods

This means that in some cases, I’ll recommend weight loss before surgery. That’s a medical recommendation based on statistics. Generally a BMI above 40 carries a far higher risk with respect to anaesthetics and surgical risk factors. 

It also doesn’t mean that patients with a high BMI can’t have surgery. Each case is assessed individually, considering overall health, functional limitation, and the likely balance of risk vs benefit.

If you’ve been told your BMI is “too high” for surgery and you’d like a thorough assessment — ask your GP about a specialist referral.

Dr Chien-Wen Liew | Adelaide Hip & Knee Replacement Surgeon
drchienwenliew.com.au

⚠️ General educational information only. Individual treatment decisions should be made in consultation with your own medical team.""",
"hashtags":"#BMIAndSurgery #HipReplacement #KneeReplacement #AdelaideOrthopaedicSurgeon #Orthopaedics360 #JointHealth #SurgicalRisk #PatientEducation #AdelaideHealth #Arthroplasty #DrChienWenLiew",
"website_link":"https://drchienwenliew.com.au/blog/nutrition-and-joint-replacements/","image_file":"2026-05-03-instagram.jpg",
"nanobanana_prompt":""},

{"id":22,"date":"2026-05-04","day":"Monday","platform":"LinkedIn","li_audience":"",
"format":"Post","topic":"The Role of Physiotherapy in Joint Replacement",
"caption":"""The role of physiotherapy in total joint replacement: before, during, and after.

Physiotherapy is not an adjunct to joint replacement surgery. It is an integral part of the entire process — and its value at each stage is well-supported by evidence.

Pre-operatively (“prehab”):
Emerging evidence supports pre-operative exercise — particularly quadriceps strengthening for TKR and hip abductor strengthening for THA — in improving early post-operative function. I routinely recommend prehab for suitable patients, particularly those who are significantly deconditioned.

In-hospital:
Day-of-surgery mobilisation is standard practice. Our in-hospital physiotherapy team begins weight-bearing and exercises within hours of surgery. Early mobilisation reduces VTE risk, prevents deconditioning, and supports discharge planning.

Post-discharge (community and outpatient):
This is where most of the functional recovery work happens. A structured, progressive programme for 6–12 weeks post-operatively is essential. Patients who engage fully with physiotherapy consistently achieve better functional outcomes.

For GP colleagues referring to physiotherapy:
• TKR: Quad sets, SLR, heel slides, knee flexion ROM, gait re-education
• THA: Hip abductor strengthening, balance, gait correction
• Both: Hydrotherapy from ~6 weeks when wound healed; gym-based exercise from ~8–12 weeks

If your patient is struggling with physiotherapy engagement or progress, please feel free to contact our rooms. We can provide specific guidance or arrange a post-operative review.

#PhysiotherapyAndSurgery #TotalJointReplacement #Arthroplasty #MedEd #GPReferral #AdelaideOrthopedics #HipReplacement #KneeReplacement""",
"hashtags":"",
"website_link":"https://drchienwenliew.com.au/blog/what-happens-on-the-day-of-a-hip-or-knee-replacement/","image_file":"2026-05-04-linkedin.jpg",
"nanobanana_prompt":""},

{"id":23,"date":"2026-05-05","day":"Tuesday","platform":"Instagram","li_audience":"",
"format":"Infographic","topic":"The Knee Joint: Anatomy & What Gets Replaced",
"caption":"""What actually gets replaced in a knee replacement? 🦴

Despite the name, a “knee replacement” doesn’t remove the entire knee. Here’s what actually happens.

The operation resurfaces the damaged ends of the bones with precisely shaped metal and plastic components:

🔵 Femoral component — caps the lower end of the thigh bone (femur)
🔵 Tibial tray — sits on the top of the shin bone (tibia)
🔵 Polyethylene insert — a smooth plastic spacer between the metal components
🔵 Patellar component — resurfaces the underside of the kneecap (in most cases)

Your own ligaments, tendons, and muscles remain intact — the implants simply recreate the smooth joint surface that arthritis has destroyed.

The result: pain relief and restored movement.

Dr Chien-Wen Liew | Adelaide Hip & Knee Replacement Surgeon
More at drchienwenliew.com.au 🔗 Link in bio

⚠️ General educational information only. Individual treatment decisions should be made in consultation with your own medical team.""",
"hashtags":"#KneeReplacement #TKR #KneeAnatomy #AdelaideOrthopaedicSurgeon #Orthopaedics360 #TotalKneeReplacement #KneeImplant #PatientEducation #BoneHealth #AdelaideHealth #JointHealth #DrChienWenLiew",
"website_link":"https://www.youtube.com/watch?v=WvZQqRq_4mI","image_file":"2026-05-05-instagram.jpg",
"nanobanana_prompt":""},

{"id":24,"date":"2026-05-05","day":"Tuesday","platform":"Facebook","li_audience":"",
"format":"Post + Link","topic":"Total Knee Replacement in Adelaide",
"caption":"""Total knee replacement: what to expect from Dr Liew’s approach in Adelaide.

Knee arthritis is one of the most common reasons people seek orthopaedic care — and total knee replacement remains one of the most effective surgical interventions available for end-stage disease.

At Orthopaedics 360, my approach to total knee replacement prioritises four things: patient selection and timing, precision in the operating room, multimodal pain management to support early recovery, and a structured rehabilitation programme that begins on the day of surgery.

Most patients are walking with support on the same day as their operation. The majority go home within 1–3 days and return to light activity within 6 weeks.

If you’ve been living with knee pain that’s significantly affecting your daily life despite conservative management, the right next step is a conversation with your GP about a specialist referral.

I’ve written a detailed overview of the procedure and what to expect at the link below.

This post contains general educational information only. Please consult your GP or specialist for advice tailored to your situation.""",
"hashtags":"#AdelaideHealth #KneeReplacement #TotalKneeReplacement #OrthopaedicSurgery #SouthAustralia #Orthopaedics360",
"website_link":"https://drchienwenliew.com.au/blog/total-knee-replacement-adelaide/","image_file":"2026-05-05-facebook.jpg",
"nanobanana_prompt":""},

{"id":25,"date":"2026-05-07","day":"Thursday","platform":"Instagram","li_audience":"",
"format":"Carousel","topic":"Hip Replacement Approaches Compared",
"caption":"""Not all hip replacements are done the same way. 💡

Swipe to understand the three main surgical approaches — and what makes each one different →

There are several approaches to hip replacement surgery, each with a different incision site, muscle management, and recovery profile. The right approach depends on your anatomy, your surgeon’s expertise, and your individual goals.

The three most common approaches:
🔵 Posterior (most widely used worldwide)
🔵 Lateral / Direct Lateral
🔵 Anterior (Direct Anterior Approach)

No single approach is best for every patient. The most important factor is a surgeon experienced in the technique they use, operating in a well-equipped facility.

Dr Chien-Wen Liew | Adelaide Hip & Knee Replacement Surgeon
More at drchienwenliew.com.au 🔗 Link in bio

⚠️ General educational information only. Individual treatment decisions should be made in consultation with your own medical team.""",
"hashtags":"#HipReplacement #AnteriorHipReplacement #DirectAnteriorApproach #AdelaideOrthopaedicSurgeon #Orthopaedics360 #TotalHipReplacement #HipSurgery #PatientEducation #AdelaideHealth #JointReplacement #DrChienWenLiew",
"website_link":"https://drchienwenliew.com.au/blog/what-is-the-best-approach-for-total-hip-replacements/","image_file":"2026-05-07-instagram.jpg",
"nanobanana_prompt":""},
]
