# All posts – captions, hashtags, image filenames
# ─────────────────────────────────────────────────
# DO NOT EDIT THIS FILE DIRECTLY.
# Edit posts_schedule.xlsx instead, then run:
#   Regenerate Posts from Excel.command
# ─────────────────────────────────────────────────

DISCLAIMER_IG = "\n\n\u26a0\ufe0f General educational information only. Individual treatment decisions should be made in consultation with your own medical team."
DISCLAIMER_FB = "\n\nThis post contains general educational information only. Please consult your GP or specialist for advice tailored to your situation."

POSTS = [
]
